name = "BTA! Plus"
author = "camoweed"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63e12e1acbff649fca08e7e1e7a15fc2160cbf51d3a68f77df4011c2cdbfdb76"

[versions]
bta = "8.0"
fabric = "0.18.4-bta.11"
minecraft = "b1.7.3"
unsup = "1.2.7"

[options]
acceptable-game-versions = ["b1.7.3"]
