name = "BTA! Plus"
author = "camoweed"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ce0b1f603c31a1a743bf0ed8a0e57da484dced04b0357c945b82818cbcdd73e"

[versions]
bta = "8.0"
fabric = "0.18.4-bta.11"
minecraft = "b1.7.3"
unsup = "1.2.7"

[options]
acceptable-game-versions = ["b1.7.3"]
